### ISSUE TITLE
Problem installing on Laravel 5.4.23

### ISSUE THREAD

**Issue by NPTPolynomial** [igaster/laravel-theme#57]
Hi,

I followed the steps on the installation page. However, on the last step it errors and I don't know what to do. Please help. I have attached some pictures of the progress here:

**Composer - Installation:**

![screen shot 2017-06-27 at 1 12 24 pm](https://user-images.githubusercontent.com/14267078/27608010-b0cc78fe-5b3a-11e7-81c7-a459244c23b8.png)

**Add into configuration arrays - App.php**

![screen shot 2017-06-27 at 1 16 06 pm](https://user-images.githubusercontent.com/14267078/27608087-fbd7a2f6-5b3a-11e7-9d18-26de3d4e6905.png)

![screen shot 2017-06-27 at 1 16 12 pm](https://user-images.githubusercontent.com/14267078/27608096-01e1aa8e-5b3b-11e7-873f-f0d3c741592f.png)

**Here is the error:**

![screen shot 2017-06-27 at 1 11 21 pm](https://user-images.githubusercontent.com/14267078/27608117-179f338c-5b3b-11e7-9940-970f1766fd92.png)

When the line on the provider array is removed, config rebuilds cache correctly.

I also run into the same problem when trying to publish.

![screen shot 2017-06-27 at 1 19 08 pm](https://user-images.githubusercontent.com/14267078/27608167-49ab851a-5b3b-11e7-9b7f-d606ab2f7d24.png)

Please help!

**Comment by GaryCornell** [comment]
I just installed a new container in my Hyper-V, running Ubuntu 16x / PHP 7 and will install latest Laravel 5.4x so I will give it a shot and see if I can reproduce the issue. What version of PHP are you running cause there have been reported issues with foreach calls between PHP 5 and 7, I have dealt with a few myself. Hope to help and will get back to you asap.

I did install this on my main dev container running the same versions as above with a few minor issues but nothing dealing with foreach errors.

In your stack trace what file threw the error? There are quite a few foreach calls in the theme app and none in the provider so its a bit confusing without more info.

**Comment by NPTPolynomial** [comment]
Hi Gary,

Thank you for the quick reply. I got a screenshot of the log. It says line 242 where it is scanning for themes. 

![screen shot 2017-06-27 at 9 46 13 pm](https://user-images.githubusercontent.com/14267078/27620965-3d3ab39a-5b82-11e7-8b9f-86b9ea27765c.png)

I tried making a theme folder in public/ and resources/ and resources/views but it did not detect anything.

Thank you for helping me

**Comment by GaryCornell** [comment]
Did you use the command console to create your theme? This is the easiest way and makes sure all goes well. Plus it will generate the theme.json file automatically

Try this and see what happens, if all goes well then we can whittle this down further

From command line in apps root
```
php artisan theme:create ThemeNameHere
```
or just
```
php artisan theme:create
```

follow the prompts fill in the fields, theme name, assets name (Same as theme name) etc.

Then run
```
php artisan theme:list
```

Should show something like this

+----------------------+----------------------+----------------------+----------------------+
|      Theme Name      |        Extends       |      Views Path      |      Asset Path      |
+----------------------+----------------------+----------------------+----------------------+
| ThemeName             |       -------                | ThemeName               | ThemeName          |
+----------------------+----------------------+----------------------+----------------------+
Views Path is relative to: /path_to/resources/views/ThemeName
Asset Path is relative to: /path_to/public


Now in config/themes.php set

'default' => 'ThemeName',

This is the simplest way at least to see if it works. I just finished installing php on my server and going to try and install shortly.

Also see if these commands show errors
```
php composer.phar dump-autoload
php artisan view:clear
php artisan config:cache
```

**Comment by GaryCornell** [comment]
Looks to me like you are not setting the theme name properly in config/themes.php
```
        // Add themes from config/themes.php
        foreach ($themesConfig as $themeName => $themeConfig) {
```

Make sure to delete any folders you created manually and try creating from commandline as show in above post

**Comment by igaster** [comment]
Hello @NPTPolynomial, it seems that when the configuration file is not published then it doesn't fallback to the correct defaults. I've just published a new version 2.0.2. I hope it solves the problem. Can you check it?

**Comment by igaster** [comment]
@GaryCornell did you face the same issue on a new installation?

**Comment by GaryCornell** [comment]
> Hello @NPTPolynomial, it seems that when the configuration file is not published then it doesn't fallback to the correct defaults. I've just published a new version 2.0.2. I hope it solves the problem. Can you check it?

That was my next idea, if the themes config isn't present then nothing is found foreach thus the error, worst case scenario if still wont publish copy over to config manually.

**Comment by NPTPolynomial** [comment]
Thank you guys for the help. It worked!

Version 2.0.2 fixed it!

**Comment by GaryCornell** [comment]
Awesome time to update my code...
